### PR TITLE
Support 'when' for class methods

### PR DESCRIPTION
**Pull request by uttamk**
Patching for class methods is broken. Add an extra condition to patch class
methods. The following test is broken
```python
        when(targetpackage.TheClass).some_class_method(1).then_return(10)
        when(targetpackage.TheClass).some_class_method(2).then_return(11)

        assert_that(targetpackage.TheClass.some_class_method(1), equal_to(10))
        assert_that(targetpackage.TheClass.some_class_method(2), equal_to(11))
```

### CODE REVIEW

**Comment by uttamk** [comment]
Using 'type' directly instead of TypeType seems to work on python3 as well.

**Comment by uttamk** [comment]
@aelgru https://github.com/aelgru/fluentmock/pull/42 should fix it ??

**Comment by uttamk** [comment]
I guess that is because in your example C is an old style class. The following code works.
```python
class D(object):
   ...:     pass

In [5]: isinstance(D, type)
Out[5]: True
```
 Should the library support old style classes ??

**Comment by uttamk** [comment]
@aelgru now both new style and old style classes will be handled. Any thoughts ?

**Comment by aelgru** [comment]
Thank you very much for your contribution.

**Comment by uttamk** [comment]
@aelgru can you create a new release for this, then I can directly use the github ref in my requirements.txt (otherwise I would have to refer to my forked version). Thanks in advance

**Comment by aelgru** [comment]
[v0.3.2](https://pypi.python.org/pypi/fluentmock/0.3.2) released. Thanks again.

**Pull request merged**
